name: Nuget Release

on:
  create:
    tag: 
      - '*.*.*'

jobs:
  package:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies    
      working-directory: ./RiotSharpExtensions
      run: dotnet restore
    - name: Build
      working-directory: ./RiotSharpExtensions
      run: dotnet build --no-restore
    - name: Test
      working-directory: ./RiotSharpExtensions
      run: dotnet test --no-build --verbosity normal
    - name: Build Nuget
      working-directory: ./nuget
      run: nuget pack -version ${{ steps.get_version.outputs.VERSION }}
    - name: Publish Nuget
      working-directory: ./nuget
      run: nuget push RiotSharpExtensions.${{ steps.get_version.outputs.VERSION }}.nupkg -ApiKey ${{secrets.NUGET_API_KEY}} -src nuget.org
